--- 
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo
  labels:
    name: demo-namespc
  namespace: my-dev 
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchLabels:
      name: demo-ng
  template:    
    metadata:
      name: demo
      labels:
        name: demo-ng
    spec:
      containers:
        - name: ngc
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP    