--- 
apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    name: demo-namespc
  namespace: my-dev 
spec:
  containers:
    - image: nginx
      name: nginxc
      ports:
        - containerPort: 80
          protocol: TCP